version: "3.8"
services:
  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883" # Port MQTT chính
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  # Database
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432" # Port Postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=vibraguard_db # Đặt tên DB theo dự án
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mosquitto-data:
  mosquitto-log:
  postgres-data:
